export const pets = [
  {
    id: 1,
    img: "images/dog.png",
    breed: "Great dane",
    category: "Dog",
    status: "Available",
    isAvailable: true,
  },
  {
    id: 2,
    img: "images/dog.png",
    breed: "Great dane",
    category: "Dog",
    status: "Available",
    isAvailable: true,
  },
  {
    id: 3,
    img: "images/dog.png",
    breed: "Great dane",
    category: "Dog",
    status: "Sold",
    isAvailable: true,
  },
  {
    id: 4,
    img: "images/dog.png",
    breed: "Great dane",
    category: "Dog",
    status: "Available",
    isAvailable: true,
  },
  {
    id: 5,
    img: "images/dog.png",
    breed: "Great dane",
    category: "Dog",
    status: "Available",
    isAvailable: true,
  },
];
export const customers = [
  {
    id: 1,
    img: "images/human.png",
    name: "moyeen",
    email: "moyeen@yahoo.com",
    phone: "0901234676",
  },
  {
    id: 2,
    img: "images/human.png",
    name: "moyeen",
    email: "moyeen@yahoo.com",
    phone: "0901234676",
  },
  {
    id: 3,
    img: "images/human.png",
    name: "moyeen",
    email: "moyeen@yahoo.com",
    phone: "0901234676",
  },
  {
    id: 4,
    img: "images/human.png",
    name: "moyeen",
    email: "moyeen@yahoo.com",
    phone: "0901234676",
  },
  {
    id: 5,
    img: "images/human.png",
    name: "moyeen",
    email: "moyeen@yahoo.com",
    phone: "0901234676",
  },
];

export const orders = [
  {
    id: 1,
    img: "images/human.png",
    name: "moyeen",
    email: "moyeen@yahoo.com",
    phone: "0901234676",
    address: "Inlaks Plot 1611 Adeola Hopewell VI Lagos",
  },
  {
    id: 2,
    img: "images/human.png",
    name: "moyeen",
    email: "moyeen@yahoo.com",
    phone: "0901234676",
    address: "Inlaks Plot 1611 Adeola Hopewell VI Lagos",
  },
  {
    id: 3,
    img: "images/human.png",
    name: "moyeen",
    email: "moyeen@yahoo.com",
    phone: "0901234676",
    address: "Inlaks Plot 1611 Adeola Hopewell VI Lagos",
  },
  {
    id: 4,
    img: "images/human.png",
    name: "moyeen",
    email: "moyeen@yahoo.com",
    phone: "0901234676",
    address: "Inlaks Plot 1611 Adeola Hopewell VI Lagos",
  },
  {
    id: 5,
    img: "images/human.png",
    name: "moyeen",
    email: "moyeen@yahoo.com",
    phone: "0901234676",
    address: "Inlaks Plot 1611 Adeola Hopewell VI Lagos",
  },
];
